/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createIsAliveResponseFromDiscriminatorValue, type IsAliveResponse } from '../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /is-alive
 */
export interface IsAliveRequestBuilder extends BaseRequestBuilder<IsAliveRequestBuilder> {
    /**
     * Returns a simple HTTP response if the API is running.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of IsAliveResponse
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<IsAliveResponse | undefined>;
    /**
     * Returns a simple HTTP response if the API is running.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Metadata for all the requests in the request builder.
 */
export const IsAliveRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createIsAliveResponseFromDiscriminatorValue,
    },
};
/**
 * Uri template for the request builder.
 */
export const IsAliveRequestBuilderUriTemplate = "{+baseurl}/is-alive";
/* tslint:enable */
/* eslint-enable */
